BusinessBundle\Entity\Event:
    properties:
        status:
            - BusinessBundle\Validator\Constraints\ConstraintsEventStatus: ~

        country:
            - NotBlank: { message: 'country is required' }
            - Regex:
                pattern: '/^[A-Z]|[a-z]/'
                message: "Only string are permitted"
            - Length:
                max: 3
                maxMessage: "3 characters are permitted for country field"

        customerRef:
            - Regex:
                pattern: '/^[A-Z]|[a-z]/'
                message: "Only string are permitted"
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for customerRef field"

        city:
            - NotBlank: { message: 'city is required' }
            - Regex:
                pattern: '/^[A-Z]|[a-z]/'
                message: "Only string are permitted"
            - Length:
                max: 255
                maxMessage: "3 characters are permitted for country field"

        website:
            - Regex:
                pattern: '/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/'
                message: "website url is not valid"
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for website field"

        venue:
            - NotBlank: { message: 'venue is required' }
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for venue field"

        organizer:
            - NotBlank: { message: 'organizer is required' }
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for location field"

        description:
            - NotBlank: { message: 'description is required' }
            - Length:
                max: 1000
                maxMessage: "1000 characters are permitted for detailed description field"

        contactEmail:
            - Regex:
                pattern: '/^[\w.-]+@[\w.-]+\.[a-z]{2,6}$/'
                message: This email is not valid


        startDate:
            - NotBlank: { message: 'startDate is required' }

        endDate:
            - NotBlank: { message: 'endDate is required' }

        startTime:
            - NotBlank: { message: 'startTime is required' }

        endTime:
            - NotBlank: { message: 'endTime is required' }

        title:
            - NotBlank: { message: 'title is required' }

        industries:
            - NotBlank: { message: 'industries is required' }

        eventTopic:
            - NotBlank: { message: 'eventTopic is required' }

        eventType:
            - NotBlank: { message: 'eventType is required' }

        visuel:
            - NotBlank: { message: 'visuel is required' }


