BusinessBundle\Entity\RegisterRequest:
    properties:
        email:
            - Regex:
                pattern: '/^[\w.-]+@[\w.-]+\.[a-z]{2,6}$/'
                message: This email is not valid

        status:
            - BusinessBundle\Validator\Constraints\ConstraintsRegisterRequestStatus: ~

        compagnyName:
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for compagnyName field"

        comments:
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for comments field"

        name:
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for name field"

        userId:
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for userId field"

        city:
            - Length:
                max: 255
                maxMessage: "255 characters are permitted for city field"

        country:
            - Length:
                max: 3
                maxMessage: "3 characters are permitted for country field"

        phoneNumber:
            - Regex:
                pattern: '/^([+][0-9]{1,3}[)]?)\s*[-\s\.]?[0-9]{1,3}([-\s\.]?[0-9]{3})([-\s\.]?[0-9]{3,4})$/'
                message: Phone number format is not valide