fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: jms_serializer
    indexes:
        %elastic_index%:
            types:
                event:
                    persistence:
                    # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: BusinessBundle\Entity\Event
                        listener:
                            insert: true
                            update: true
                    serializer:
                        groups: ['event']
