##---------- Application -----------------##

api.admin.get_authorized_app:
    path:  /apps
    methods: GET
    defaults: { _controller: ApiBundle:Admin\App:getAuthorizedApps }

api.admin.create_app:
    path:  /apps
    methods: POST
    defaults: { _controller: ApiBundle:Admin\App:createApp }

api.admin.update_app:
    path:  /apps/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\App:updateApp }
    requirements:
        id: '\d+'

api.admin.get_one_app:
    path:  /apps/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Admin\App:getOneApp }
    requirements:
        id: '\d+'

api.admin.enable_app:
    path:  /apps/{id}/enable
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\App:enableApp }
    requirements:
        id: '\d+'

api.admin.disable_app:
    path:  /apps/{id}/disable
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\App:disableApp }
    requirements:
        id: '\d+'

##-------------------- Customer ---------------------###

api.admin.get_authorized_customers:
    path:  /customers
    methods: GET
    defaults: { _controller: ApiBundle:Admin\Customer:getAuthorizedCustomers }

api.admin.create_customer:
    path:  /customers
    methods: POST
    defaults: { _controller: ApiBundle:Admin\Customer:createCustomer }

api.admin.update_customer:
    path:  /customers/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\Customer:updateCustomer }
    requirements:
        id: '\d+'

api.admin.get_one_customer:
    path:  /customers/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Admin\Customer:getOneCustomer }
    requirements:
        id: '\d+'

api.admin.enable_customer:
    path:  /customers/{id}/enable
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\Customer:enableCustomer }
    requirements:
        id: '\d+'

api.admin.disable_customer:
    path:  /customers/{id}/disable
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\Customer:disableCustomer }
    requirements:
        id: '\d+'