##---------- Application -----------------##

api.admin.get_authorized_app:
    path:  /apps
    methods: GET
    defaults: { _controller: ApiBundle:Admin\App:list }

api.admin.create_app:
    path:  /apps
    methods: POST
    defaults: { _controller: ApiBundle:Admin\App:create }

api.admin.update_app:
    path:  /apps/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\App:update }
    requirements:
        id: '\d+'

api.admin.get_one_app:
    path:  /apps/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Admin\App:get }
    requirements:
        id: '\d+'

api.admin.enable_app:
    path:  /apps/{id}/enable
    methods: PATCH
    defaults: { _controller: ApiBundle:Admin\App:enable }
    requirements:
        id: '\d+'

api.admin.disable_app:
    path:  /apps/{id}/disable
    methods: PATCH
    defaults: { _controller: ApiBundle:Admin\App:disable }
    requirements:
        id: '\d+'

##-------------------- Customer ---------------------###

api.admin.get_authorized_customers:
    path:  /customers
    methods: GET
    defaults: { _controller: ApiBundle:Admin\Customer:list }

api.admin.create_customer:
    path:  /customers
    methods: POST
    defaults: { _controller: ApiBundle:Admin\Customer:create }

api.admin.update_customer:
    path:  /customers/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Admin\Customer:update }
    requirements:
        id: '\d+'

api.admin.get_one_customer:
    path:  /customers/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Admin\Customer:get }
    requirements:
        id: '\d+'

api.admin.enable_customer:
    path:  /customers/{id}/enable
    methods: PATCH
    defaults: { _controller: ApiBundle:Admin\Customer:enable }
    requirements:
        id: '\d+'

api.admin.disable_customer:
    path:  /customers/{id}/disable
    methods: PATCH
    defaults: { _controller: ApiBundle:Admin\Customer:disable }
    requirements:
        id: '\d+'