##--------------- Event ------------##

api.editor.list_events:
    path: /events
    methods: GET
    defaults: { _controller: ApiBundle:Editor\Event:list }

api.editor.get_one_event:
    path: /events/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Editor\Event:get }
    requirements:
        id: '\d+'

api.editor.create_an_event:
    path: /events
    methods: POST
    defaults: { _controller: ApiBundle:Editor\Event:create }

api.editor.update_an_event:
    path: /events/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Editor\Event:update }
    requirements:
        id: '\d+'

api.editor.delete_an_event:
    path: /events/{id}
    methods: DELETE
    defaults: { _controller: ApiBundle:Editor\Event:delete }
    requirements:
        id: '\d+'

api.editor.request_publish_event:
    path: /events/{id}/status/publish-request
    methods: PATCH
    defaults: { _controller: ApiBundle:Editor\Event:publishRequest }
    requirements:
        id: '\d+'

api.editor.publish_event:
    path: /events/{id}/status/publish
    methods: PATCH
    defaults: { _controller: ApiBundle:Editor\Event:publish }
    requirements:
        id: '\d+'

api.editor.archive_event:
    path: /events/{id}/status/archive
    methods: PATCH
    defaults: { _controller: ApiBundle:Editor\Event:archive }
    requirements:
        id: '\d+'

api.editor.registration_events:
    path: /events/{id}/registrations
    methods: GET
    defaults: { _controller: ApiBundle:Editor\Event:registration }
    requirements:
        id: '\d+'

##---------------------- Value List ----------------------##

api.editor.list_tags:
    path: /value-lists
    methods: GET
    defaults: { _controller: ApiBundle:Editor\ValueList:list }

api.editor.create_tag:
    path: /value-lists
    methods: POST
    defaults: { _controller: ApiBundle:Editor\ValueList:create }

api.editor.update_tag:
    path: /value-lists/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Editor\ValueList:update }
    requirements:
        id: '\d+'

api.editor.enable_tag:
    path: /value-lists/{id}/enable
    methods: PATCH
    defaults: { _controller: ApiBundle:Editor\ValueList:enable }
    requirements:
        id: '\d+'

api.editor.disable_tag:
    path: /value-lists/{id}/disable
    methods: PATCH
    defaults: { _controller: ApiBundle:Editor\ValueList:disable }
    requirements:
        id: '\d+'

