api.public.list_events:
    path: /events
    methods: GET
    defaults: { _controller: ApiBundle:Pub\Event:list }

api.public.get_one_event:
    path: /events/{id}
    methods: GET
    defaults: { _controller: ApiBundle:Pub\Event:get }
    requirements:
        id: '\d+'

api.public.inscription_to_event:
    path: /events/{id}/register‐request
    methods: POST
    defaults: { _controller: ApiBundle:Pub\Event:inscriptionRequest }
    requirements:
        id: '\d+'

api.user.event_inscription:
    path: /user/{user_id}/events/registered‐event
    methods: GET
    defaults: { _controller: ApiBundle:Pub\Event:userEvent }


##---------------------- Value List ----------------------##

api.public.list_value_list:
    path: /value-lists
    methods: GET
    defaults: { _controller: ApiBundle:Pub\ValueList:list }

api.public.create_value_list:
    path: /value-lists
    methods: POST
    defaults: { _controller: ApiBundle:Pub\ValueList:create }

api.public.update_value_list:
    path: /value-lists/{id}
    methods: PUT
    defaults: { _controller: ApiBundle:Pub\ValueList:update }
    requirements:
        id: '\d+'

api.public.enable_value_list:
    path: /value-lists/{id}/enable
    methods: PATCH
    defaults: { _controller: ApiBundle:Pub\ValueList:enable }
    requirements:
        id: '\d+'

api.public.disable_value_list:
    path: /value-lists/{id}/disable
    methods: PATCH
    defaults: { _controller: ApiBundle:Pub\ValueList:disable }
    requirements:
        id: '\d+'
