BusinessBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: BusinessBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: true
    fields:
        deletedAt:
            type: date
            nullable: true
        customerRef:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
            unique: true
        date:
            type: datetime
            nullable: true
        detailedDescription:
            type: string
            length: '1000'
        website:
            type: string
            length: 255
        country:
            type: string
            length: '3'
        location:
            type: string
            length: 255
        city:
            type: string
            length: 255
        typeOfEvent:
            type: string
            length: 255
        industry:
            type: string
            length: 255
        thematicTag:
            type: string
            length: 255
        nameOfOrganizer:
            type: string
            length: 255
        contactForm:
            type: string
            length: 255
        attachment:
            type: string
            length: 255
        socialMediaSharing:
            type: array
        status:
            type: string
            length: '30'
        visuel:
            type: json_array
        illustrations:
            type: array

    oneToMany:
        requestRegisters:
            targetEntity: RegisterRequest
            mappedBy: event
            cascade: [remove]

    lifecycleCallbacks: {  }
