BusinessBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: BusinessBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: true
    fields:
        deletedAt:
            type: date
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        publishedAt:
            type: datetime
            nullable: true
        customerRef:
            type: string
            length: 255
        title:
            type: string
            length: 255
        startDate:
            type: date
            nullable: true
        endDate:
            type: date
            nullable: true
        startTime:
            type: time
            nullable: true
        endTime:
            type: time
            nullable: true
        description:
            type: string
            length: '1000'
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: '3'
            nullable: true
        venue:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
        organizer:
            type: string
            length: 255
            nullable: true
        contactEmail:
            type: string
            length: 255
            nullable: true
        attachment:
            type: string
            length: 255
            nullable: true
        socialMediaSharing:
            type: array
            nullable: true
        status:
            type: string
            length: '30'
        visuel:
            type: json_array
            nullable: true
        illustrations:
            type: json_array
            nullable: true
        availableSeats:
            type: integer
            nullable: true

    oneToMany:
        requestRegisters:
            targetEntity: RegisterRequest
            mappedBy: event
            cascade: [remove]

    manyToMany:
        industries:
            targetEntity: ValueList
            cascade: [persist]
            joinTable:
                name: event_industry

        eventTopic:
            targetEntity: ValueList
            cascade: [persist]
            joinTable:
                name: event_topic

        eventType:
            targetEntity: ValueList
            cascade: [persist]
            joinTable:
                name: event_type
        agendas:
            targetEntity: BusinessBundle\Entity\Agenda
            inversedBy: events
            cascade: [persist]
            joinTable:
              name: events_agendas
              joinColumns:
                event_id:
                  referencedColumnName: id
              inverseJoinColumns:
                agenda_id:
                  referencedColumnName: id
    lifecycleCallbacks:
         prePersist: [setCreatedAt]
         preUpdate: [setUpdatedAt]

