BusinessBundle\Entity\RegisterRequest:
    type: entity
    table: null
    repositoryClass: BusinessBundle\Repository\RegisterRequestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: true
    fields:
        deletedAt:
            type: date
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        userId:
            type: string
            length: 255
            nullable: true
        compagnyName:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        phoneNumber:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
            nullable: true
        comments:
            type: string
            length: '1000'
            nullable: true
        status:
            type: string
            length: '30'
        numberOfSeats:
            type: integer
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: requestRegisters

    lifecycleCallbacks: {  }
