BusinessBundle\Entity\ValueList:
    type: entity
    table: null
    repositoryClass: BusinessBundle\Repository\ValueListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        domain:
            type: string
            length: '100'
            column: domain_value
        key:
            type: string
            length: '100'
            column: key_value
        value:
            type: string
            length: 255
            column: value_content
        enable:
            type: boolean
    lifecycleCallbacks: {  }
