services:
    api.event_manager:
        class: BusinessBundle\Manager\EventManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - BusinessBundle\Entity\Event
            - %default_limit%
            - %default_offset%

    api.value_list_manager:
        class: BusinessBundle\Manager\ValueListManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - BusinessBundle\Entity\ValueList
            - %default_limit%
            - %default_offset%

    api.register_request_manager:
        class: BusinessBundle\Manager\RegisterRequestManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - BusinessBundle\Entity\RegisterRequest
            - %default_limit%
            - %default_offset%

    api.elastic_manager:
        class: BusinessBundle\Manager\ElasticManager
        arguments:
            - "@fos_elastica.finder.api_event.event"




