services:
#    business.example:
#        class: BusinessBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api.validator.event_date:
        class: BusinessBundle\Validator\Constraints\ConstraintsTextToDateTimeValidator
        tags:
            - { name: validator.constraint_validator, alias: format_date_event_not_valid}
