services:
#    business.example:
#        class: BusinessBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api.validator.event_date:
        class: BusinessBundle\Validator\Constraints\ConstraintsTextToDateTimeValidator
        tags:
            - { name: validator.constraint_validator, alias: format_date_event_not_valid}

    api.validator.event_status:
        class: BusinessBundle\Validator\Constraints\ConstraintsEventStatusValidator
        tags:
            - { name: validator.constraint_validator, alias: status_event_not_valid}

    api.validator.register_request_status:
        class: BusinessBundle\Validator\Constraints\ConstraintsRegisterRequestStatusValidator
        tags:
            - { name: validator.constraint_validator, alias: status_register_request_not_valid}

    api.import_business_data:
        class: BusinessBundle\Service\ImportBusinessDataService
        arguments:
            - "@api.value_list_manager"

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]