<?php

namespace BusinessBundle\Repository;

/**
 * ValueListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueListRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $filterParams
     * @return \Doctrine\ORM\Query
     */
    public function getValueLists($filterParams)
    {
        $qb = $this->createQueryBuilder('v');

         if (!empty($filterParams['domain'])) {
             $qb
                 ->where('v.domain LIKE :domain')
                 ->setParameter('domain', '%'.$filterParams['domain'].'%');
         };

        return $qb->getQuery();
    }
}
