<?php

namespace ApiSecurityBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * AppClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppClientRepository  extends EntityRepository
{
    /**
     * @param array $params
     * @return array
     */
    public function getApps(array $params)
    {
        $offset = !empty($params['offset']) ? $params['offset'] : $params['defaultOffset'];
        $limit = !empty($params['limit']) ? $params['limit'] : $params['defaultLimit'];
        $qb = $this->createQueryBuilder('a')
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $request
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function loadUserByUsername($request) {

        $login = $request->headers->get('login');
        $qb = $this->createQueryBuilder('a')
            ->where('a.login =:login')
            ->setParameter('login', $login);

        return $qb->getQuery()->getOneOrNullResult();

        $qb->getQuery()->getOneOrNullResult();

    }

}
